name: Jetcaster

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Jetcaster.yaml'
      - 'Jetcaster/**'
  pull_request:
    paths:
      - '.github/workflows/Jetcaster.yaml'
      - 'Jetcaster/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-sample.yml
    with:
      name: Jetcaster
      path: Jetcaster
      module: mobile
    secrets:
      compose_store_password: ${{ secrets.COMPOSE_STORE_PASSWORD }}
      compose_key_alias: ${{ secrets.COMPOSE_KEY_ALIAS }}
      compose_key_password: ${{ secrets.COMPOSE_KEY_PASSWORD }}
